name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install  # Installs dependencies if needed by your script
    
    - name: Run generatePackagedPlayer.js
      run: |
        node generatePackagedPlayer.js "Quadrolax World" "fields" '{"embedAssets": false}' false

    - name: Rename example file to index.html
      run: |
        mv ./PackagedPlayers/Quadrolax\ World/Quadrolax\ World.html ./index.html

    - name: Move assets
      run: |
        mv ./PackagedPlayers/Quadrolax\ World/music/ ./music/
        mv ./PackagedPlayers/Quadrolax\ World/sounds/ ./sounds/

    - name: Cleanup
      run: |
        find . -mindepth 1 \
          -not -name 'index.html' \
          -not -name 'sounds' \
          -not -name 'music' \
          -delete

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./
        publish_branch: gh-pages
        commit_message: 'Deploy index.html as main page'
        github_token: ${{ secrets.GITHUB_TOKEN }}

