name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger the workflow when changes are pushed to the `main` branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Move Quadrolax World.html to root
      run: |
        mv ./PackagedPlayers/Quadrolax\ World.html ./Quadrolax\ World.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./  # Directory to deploy (root folder)
        publish_branch: gh-pages  # Branch to deploy to
        commit_message: 'Deploy Quadrolax World.html as main page'
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the default GitHub token

    - name: Clean up (optional)
      run: |
        rm ./Quadrolax\ World.html  # Optionally clean up the file after deployment
