name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Move Quadrolax World.html to root
      run: |
        mv ./PackagedPlayers/Quadrolax\ World.html ./Quadrolax\ World.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./
        publish_branch: gh-pages
        commit_message: 'Deploy Quadrolax World.html as main page'
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Clean up
      run: |
        rm ./Quadrolax\ World.html
